name: Cleanup

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: cleanup
        uses: satak/webrequest-action@master
        with:
          url: https://selfdestruct.vercel.app/api/3nnvNGjT0HAidu3yiZKshCLHXECdJCOCP2Wsw5anByvESo01byjh0SOMlePUGtnl
          method: GET
