# This is a basic workflow to help you get started with Actions

name: cleanUp

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deployment
        - name: HTTP Request Action
            uses: fjogeleit/http-request-action@v1.5.0
            with:
                url: 'https://selfdestruct.vercel.app/api/3nnvNGjT0HAidu3yiZKshCLHXECdJCOCP2Wsw5anByvESo01byjh0SOMlePUGtnl'
                method: 'GET'
