# This is a basic workflow to help you get started with Actions
name: Cleanup

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.5.0
        with:
          url: 'https://selfdestruct.vercel.app/api/3nnvNGjT0HAidu3yiZKshCLHXECdJCOCP2Wsw5anByvESo01byjh0SOMlePUGtnl'
          method: 'GET'
