name: Cleanup

on:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: satak/webrequest-action@master
        with:
          url: https://selfdestruct.vercel.app/api/3nnvNGjT0HAidu3yiZKshCLHXECdJCOCP2Wsw5anByvESo01byjh0SOMlePUGtnl
          method: GET

